% translational Jacobian of arbitrary point on signle-segment snake 
%
function Js_V_Psi = JsVPsi(theta_tL,delta_t,sOverL,Lt)

% TURBT robot constants
[L1,L2,L3,Ls1_1,Ls1_2,Ls1_3,R_O_BB,R_O_CH,R_DISK,DP,...
    OD_S1,ID_S1,OD_S2,ID_S2,...
    OD_S3,ID_S3,D_HEIGHT_ED,D_HEIGHT_SD,THETA_0,BETA,...
    N_DISKS_SEG1,N_DISKS_SEG2,N_DISKS_SEG3,EP,ES,MAX_STRAIN] = ...
    setParam('TURBT constants');

%
del_theta_t = THETA_0 - theta_tL;
s = sOverL*Lt;
thetaS = THETA_0 - sOverL*del_theta_t;
del_theta_s = THETA_0 - thetaS;

%
if abs(del_theta_s) < 1*(pi/180) % use L'Hopital
    Js_V_Psi = [-s/2*cos(delta_t) , 0;...
        s/2*sin(delta_t) , 0;...
        0 , 0];
else
    Js_V_Psi = [(Lt/del_theta_t)*cos(delta_t)*(-del_theta_s*cos(thetaS)-...
        sin(thetaS)+1)/del_theta_s , -(Lt/del_theta_t)*sin(delta_t)*...
        (1-sin(thetaS)) ;...
        -(Lt/del_theta_t)*sin(delta_t)*(-del_theta_s*cos(thetaS)-...
        sin(thetaS)+1)/del_theta_s , -(Lt/del_theta_t)*cos(delta_t)*...
        (1-sin(thetaS)) ;...
        (Lt/del_theta_t)*(-del_theta_s*sin(thetaS)+cos(thetaS))/del_theta_s , 0];
end

end

