% translational Jacobian of single-segment snak
%
function Jt_v_sai = Jtvsai(theta_tL , delta_t , Lt)
% TURBT robot constants
[L1,L2,L3,Ls1_1,Ls1_2,Ls1_3,R_O_BB,R_O_CH,R_DISK,DP,...
    OD_S1,ID_S1,OD_S2,ID_S2,...
    OD_S3,ID_S3,D_HEIGHT_ED,D_HEIGHT_SD,THETA_0,BETA,...
    N_DISKS_SEG1,N_DISKS_SEG2,N_DISKS_SEG3,EP,ES,MAX_STRAIN] = ...
    setParam('TURBT constants');

%
del_theta_t = theta_tL - THETA_0;
if abs(theta_tL-pi/2) < 1*(pi/180) % use L'Hopital
    Jt_v_sai = [-Lt/2*cos(delta_t) , 0;...
        Lt/2*sin(delta_t) , 0;...
        0 , 0];
else
    Jt_v_sai = [Lt*cos(delta_t)*(del_theta_t*cos(theta_tL)-...
        sin(theta_tL)+1)/(del_theta_t^2) , Lt*sin(delta_t)*...
        (1-sin(theta_tL))/del_theta_t ;...
        -Lt*sin(delta_t)*(del_theta_t*cos(theta_tL)...
        -sin(theta_tL)+1)/(del_theta_t^2) , Lt*cos(delta_t)*...
        (1-sin(theta_tL))/del_theta_t ;...
        Lt*(del_theta_t*sin(theta_tL)+...
        cos(theta_tL))/del_theta_t^2 , 0];
end

end

