function P_bt_tl = Pbt_tl(theta_tL , delta_t , Lt)
% TURBT robot constants
[L1,L2,L3,Ls1_1,Ls1_2,Ls1_3,R_O_BB,R_O_CH,R_DISK,DP,...
    OD_S1,ID_S1,OD_S2,ID_S2,...
    OD_S3,ID_S3,D_HEIGHT_ED,D_HEIGHT_SD,THETA_0,BETA,...
    N_DISKS_SEG1,N_DISKS_SEG2,N_DISKS_SEG3,EP,ES,MAX_STRAIN] = ...
    setParam('TURBT constants');

if abs(theta_tL-pi/2) < 1*(pi/180)
    P_bt_tl = [0;0;Lt];
else
    delTheta = theta_tL - THETA_0;
    P_bt_tl = -(Lt/delTheta)*[cos(delta_t)*(1-sin(theta_tL)) ;...
        sin(delta_t)*(sin(theta_tL)-1) ;...
        cos(theta_tL)];
end

end
