function d_dc_to_d_psp_in_Lens = d_dc_d_psp_In_Lens_Func(in1,beta)
%D_DC_D_PSP_IN_LENS_FUNC
%    D_DC_TO_D_PSP_IN_LENS = D_DC_D_PSP_IN_LENS_FUNC(IN1,BETA)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    14-Feb-2017 15:09:54

x_0 = in1(1,:);
y_0 = in1(2,:);
z_0 = in1(3,:);
t2 = cos(beta);
t3 = x_0.^2;
t4 = y_0.^2;
t5 = t3+t4;
t6 = sqrt(t5);
t7 = sin(beta);
t8 = t2.*z_0;
t9 = t6.*t7;
t10 = t8+t9;
t11 = 1.0./t10;
t12 = t2.*t6;
t18 = t7.*z_0;
t13 = t12-t18;
t14 = t11.*t13;
t15 = atan(t14);
t16 = beta+t15;
t17 = 1.0./sqrt(t5);
t19 = 1.0./t10.^2;
t20 = z_0.^2;
t21 = t3+t4+t20;
t22 = sin(t16);
t23 = 1.0./sqrt(t21);
t24 = cos(t16);
t25 = t13.^2;
t26 = t19.*t25;
t27 = t26+1.0;
t28 = 1.0./t27;
t29 = sqrt(t21);
d_dc_to_d_psp_in_Lens = [t22.*t23.*x_0+t24.*t28.*t29.*(t2.*t11.*t17.*x_0-t7.*t13.*t17.*t19.*x_0),t22.*t23.*y_0+t24.*t28.*t29.*(t2.*t11.*t17.*y_0-t7.*t13.*t17.*t19.*y_0),0.0];
