function df_dPsp_in_Lens = df_dPsp_in_Lens_Func(positin_in_Lens,beta,rstar,fstar,q,p,d0,lens_rot_angle,lens_angle)
%DF_DPSP_IN_LENS_FUNC
%    DF_DPSP_IN_LENS = DF_DPSP_IN_LENS_FUNC(IN1,BETA,RSTAR,FSTAR,Q,P,D0,LENS_ROT_ANGLE,LENS_ANGLE)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    27-Sep-2016 11:13:08

x_0 = positin_in_Lens(1);
y_0 = positin_in_Lens(2);
z_0 = positin_in_Lens(3);
t2 = cos(beta);
t3 = sin(beta);
t4 = x_0.^2;
t5 = y_0.^2;
t6 = t4+t5;
t7 = sqrt(t6);
t8 = cos(lens_angle);
t9 = cos(lens_rot_angle);
t10 = 1.0./t6.^(3.0./2.0);
t11 = 1.0./d0;
t12 = 1.0./sqrt(t6);
t13 = t2.*t7;
t25 = t3.*z_0;
t14 = t13-t25;
t15 = t11.*t14;
t16 = t15-1.0;
t17 = p.*2.0;
t18 = t2.*z_0;
t19 = t3.*t7;
t20 = t18+t19;
t21 = 1.0./t20;
t22 = rstar.*t21;
t23 = t22.^q;
t24 = sin(lens_rot_angle);
t26 = t16.^t17;
t27 = sin(lens_angle);
t28 = t3.*t9.*t27;
t29 = t2.*t8.*t9.*t12.*x_0;
t33 = t2.*t12.*t24.*y_0;
t30 = t28+t29-t33;
t31 = t17-1.0;
t32 = t16.^t31;
t34 = 1.0./t20.^2;
t35 = q-1.0;
t36 = t22.^t35;
t37 = t3.*t24.*t27;
t38 = t2.*t9.*t12.*y_0;
t39 = t2.*t8.*t12.*t24.*x_0;
t40 = t37+t38+t39;
t41 = t3.*t8;
t43 = t2.*t12.*t27.*x_0;
t42 = t41-t43;
df_dPsp_in_Lens = reshape([fstar.*(t23.*t26.*(t2.*t8.*t9.*t12-t2.*t4.*t8.*t9.*t10+t2.*t10.*t24.*x_0.*y_0)+p.*t2.*t11.*t12.*t23.*t30.*t32.*x_0.*2.0-q.*rstar.*t3.*t12.*t26.*t30.*t34.*t36.*x_0),-fstar.*(t23.*t26.*(-t2.*t8.*t12.*t24+t2.*t4.*t8.*t10.*t24+t2.*t9.*t10.*x_0.*y_0)-p.*t2.*t11.*t12.*t23.*t32.*t40.*x_0.*2.0+q.*rstar.*t3.*t12.*t26.*t34.*t36.*t40.*x_0),fstar.*(t23.*t26.*(t2.*t12.*t27-t2.*t4.*t10.*t27)-p.*t2.*t11.*t12.*t23.*t32.*t42.*x_0.*2.0+q.*rstar.*t3.*t12.*t26.*t34.*t36.*t42.*x_0),-fstar.*(t23.*t26.*(t2.*t12.*t24-t2.*t5.*t10.*t24+t2.*t8.*t9.*t10.*x_0.*y_0)-p.*t2.*t11.*t12.*t23.*t30.*t32.*y_0.*2.0+q.*rstar.*t3.*t12.*t26.*t30.*t34.*t36.*y_0),-fstar.*(t23.*t26.*(-t2.*t9.*t12+t2.*t5.*t9.*t10+t2.*t8.*t10.*t24.*x_0.*y_0)-p.*t2.*t11.*t12.*t23.*t32.*t40.*y_0.*2.0+q.*rstar.*t3.*t12.*t26.*t34.*t36.*t40.*y_0),-fstar.*(t2.*t10.*t23.*t26.*t27.*x_0.*y_0+p.*t2.*t11.*t12.*t23.*t32.*t42.*y_0.*2.0-q.*rstar.*t3.*t12.*t26.*t34.*t36.*t42.*y_0),-fstar.*(p.*t3.*t11.*t23.*t30.*t32.*2.0+q.*rstar.*t2.*t26.*t30.*t34.*t36),-fstar.*(p.*t3.*t11.*t23.*t32.*t40.*2.0+q.*rstar.*t2.*t26.*t34.*t36.*t40),fstar.*(p.*t3.*t11.*t23.*t32.*t42.*2.0+q.*rstar.*t2.*t26.*t34.*t36.*t42)],[3, 3]);
