function distance = pointLineDistance(in1,in2,in3)
%POINTLINEDISTANCE
%    DISTANCE = POINTLINEDISTANCE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    19-Feb-2017 17:54:20

px = in3(1,:);
py = in3(2,:);
pz = in3(3,:);
ux_line = in1(1,:);
uy_line = in1(2,:);
uz_line = in1(3,:);
x0_line = in2(1,:);
y0_line = in2(2,:);
z0_line = in2(3,:);
t3 = px-x0_line;
t4 = t3.*ux_line;
t5 = py-y0_line;
t6 = t5.*uy_line;
t7 = pz-z0_line;
t8 = t7.*uz_line;
t2 = t4+t6+t8;
distance = sqrt(-t2.*(px.*ux_line.*2.0+py.*uy_line.*2.0+pz.*uz_line.*2.0)+t2.*(ux_line.*x0_line.*2.0+uy_line.*y0_line.*2.0+uz_line.*z0_line.*2.0)-px.*x0_line.*2.0-py.*y0_line.*2.0-pz.*z0_line.*2.0+px.^2+py.^2+pz.^2+t2.^2+x0_line.^2+y0_line.^2+z0_line.^2);
