function distance = seg1LineSightDistance(s1,in2,q_Ins,in4,in5,l1)
%SEG1LINESIGHTDISTANCE
%    DISTANCE = SEG1LINESIGHTDISTANCE(S1,IN2,Q_INS,IN4,IN5,L1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    19-Feb-2017 10:23:06

delta1 = in2(2,:);
theta1l = in2(1,:);
ux_ls = in4(1,:);
uy_ls = in4(2,:);
uz_ls = in4(3,:);
x0_ls = in5(1,:);
y0_ls = in5(2,:);
z0_ls = in5(3,:);
t2 = pi.*(1.0./2.0);
t3 = t2-theta1l;
t4 = 1.0./l1;
t5 = s1.*t3.*t4;
t6 = -t2+t5;
t7 = cos(t6);
t8 = 1.0./t3;
t9 = sin(t6);
t10 = t9+1.0;
t12 = l1.*t7.*t8;
t14 = q_Ins+t12-z0_ls;
t15 = t14.*uz_ls;
t16 = cos(delta1);
t17 = l1.*t8.*t10.*t16;
t18 = t17-x0_ls;
t19 = t18.*ux_ls;
t20 = sin(delta1);
t21 = l1.*t8.*t10.*t20;
t22 = t21+y0_ls;
t23 = t22.*uy_ls;
t11 = -t15-t19+t23;
t13 = q_Ins+t12;
t24 = q_Ins.*2.0;
t25 = l1.*t7.*t8.*2.0;
t26 = t24+t25;
t27 = l1.^2;
t28 = t10.^2;
t29 = 1.0./t3.^2;
distance = sqrt(-t11.*(ux_ls.*x0_ls.*2.0+uy_ls.*y0_ls.*2.0+uz_ls.*z0_ls.*2.0)-t26.*z0_ls+t11.*(t26.*uz_ls+l1.*t8.*t10.*t16.*ux_ls.*2.0-l1.*t8.*t10.*t20.*uy_ls.*2.0)+t11.^2+t13.^2+x0_ls.^2+y0_ls.^2+z0_ls.^2+t16.^2.*t27.*t28.*t29+t20.^2.*t27.*t28.*t29-l1.*t8.*t10.*t16.*x0_ls.*2.0+l1.*t8.*t10.*t20.*y0_ls.*2.0);
